import { StaffMember, UserRole } from '../types';

export const INITIAL_STAFF_LIST: StaffMember[] = [
  { id: 'st-3046', employeeId: 'A-3046', email: 'mohamed.ashhad@macl.aero', name: 'Mohamed Ashhad', role: UserRole.ITP_SUPERVISOR, status: 'active', joinDate: '2021-03-15' },
  { id: 'st-7323', employeeId: 'A-7323', email: 'abdul.qadir@macl.aero', name: 'Abdul Qadir Ibrahim', role: UserRole.ITP_OFFICER, status: 'active', joinDate: '2022-01-10' },
  { id: 'st-5582', employeeId: 'A-5582', email: 'abdulla.mushfiq@macl.aero', name: 'Abdulla Mushfiq', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-08-20' },
  { id: 'st-6155', employeeId: 'A-6155', email: 'abdulla.adam@macl.aero', name: 'Afsah Abdulla Adam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-11-05' },
  { id: 'st-5438', employeeId: 'A-5438', email: 'ahmed.ashfaq@macl.aero', name: 'Ahmed Ashfaq', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-06-12' },
  { id: 'st-6606', employeeId: 'A-6606', email: 'ahmed.azhan@macl.aero', name: 'Ahmed Azhan', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-02-14' },
  { id: 'st-7881', employeeId: 'A-7881', email: 'ahmed.humaam@macl.aero', name: 'Ahmed Humaam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-04-18' },
  { id: 'st-7000', employeeId: 'A-7000', email: 'ahmed.alaf@macl.aero', name: 'Ahmed Alaf', role: UserRole.ITP_OFFICER, status: 'active', joinDate: '2021-12-01' },
  { id: 'st-5989', employeeId: 'A-5989', email: 'ahmed.jinaan@macl.aero', name: 'Ahmed Jinaan', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-09-25' },
  { id: 'st-3036', employeeId: 'A-3036', email: 'ahmed.jumail@macl.aero', name: 'Ahmed Jumail', role: UserRole.ITP_SUPERVISOR, status: 'active', joinDate: '2020-05-10' },
  { id: 'st-8724', employeeId: 'A-8724', email: 'ali.aleef@macl.aero', name: 'Ali Aleef', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-08-01' },
  { id: 'st-3047', employeeId: 'A-3047', email: 'a.ibrahim@macl.aero', name: 'Ali Ibrahim', role: UserRole.ITP_OFFICER, status: 'active', joinDate: '2020-06-15' },
  { id: 'st-3292', employeeId: 'A-3292', email: 'ali.shihan@macl.aero', name: 'Ali Shihaan', role: UserRole.ITP_HD_OPERATOR, status: 'active', joinDate: '2020-09-01' },
  { id: 'st-8027', employeeId: 'A-8027', email: 'ali.razzan@macl.aero', name: 'Ali Razzan Hassan Rasheed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-05-12' },
  { id: 'st-7271', employeeId: 'A-7271', email: 'anoof.shareef@macl.aero', name: 'Anoof Shareef', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-12-20' },
  { id: 'st-8276', employeeId: 'A-8276', email: 'hassan.ashfag@macl.aero', name: 'Hassan Ashfag Mohamed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-06-10' },
  { id: 'st-6422', employeeId: 'A-6422', email: 'hassan.naajee@macl.aero', name: 'Hassan Naajee', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-12-30' },
  { id: 'st-6252', employeeId: 'A-6252', email: 'hassan.shahum@macl.aero', name: 'Hassan Shahum', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-11-15' },
  { id: 'st-3639', employeeId: 'A-3639', email: 'hussain.asir@macl.aero', name: 'Hussain Asir', role: UserRole.ITP_HD_OPERATOR, status: 'active', joinDate: '2020-11-20' },
  { id: 'st-6102', employeeId: 'A-6102', email: 'hussain.shinaan@macl.aero', name: 'Hussain Shinaan', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-10-10' },
  { id: 'st-6600', employeeId: 'A-6600', email: 'ibr.hamdhan@macl.aero', name: 'Ibrahim Hamdhan', role: UserRole.ADMIN, status: 'active', joinDate: '2020-01-01' },
  { id: 'st-10785', employeeId: 'A-10785', email: 'itp@macl.aero', name: 'Hassan Sammah', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-15' },
  { id: 'st-9117', employeeId: 'A-9117', email: 'a.tholaal@macl.aero', name: 'Ahmed Tholaal', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-09-20' },
  { id: 'st-5384', employeeId: 'A-5384', email: 'jazleen.jaufar@macl.aero', name: 'Jazleen Jaufar', role: UserRole.FINANCE, status: 'active', joinDate: '2021-05-15' },
  { id: 'st-2708', employeeId: 'A-2708', email: 'mohamed.ameez@macl.aero', name: 'Mohamed Ameez', role: UserRole.ITP_MANAGER, status: 'active', joinDate: '2019-08-10' },
  { id: 'st-8026', employeeId: 'A-8026', email: 'mohamed.jumaan@macl.aero', name: 'Mohamed Jumaan', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-05-10' },
  { id: 'st-5811', employeeId: 'A-5811', email: 'mohamedmaadhih@macl.aero', name: 'Mohamed Maadhih', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-09-01' },
  { id: 'st-4716', employeeId: 'A-4716', email: 'mohamed.munawwaru@macl.aero', name: 'Mohamed Munawwaru', role: UserRole.ITP_OFFICER, status: 'active', joinDate: '2021-02-14' },
  { id: 'st-4718', employeeId: 'A-4718', email: 'm.naseem@macl.aero', name: 'Mohamed Naseem', role: UserRole.ITP_OFFICER, status: 'active', joinDate: '2021-02-15' },
  { id: 'st-4707', employeeId: 'A-4707', email: 'mohamed.naveez@macl.aero', name: 'Mohamed Naveez', role: UserRole.ITP_OFFICER, status: 'active', joinDate: '2021-02-10' },
  { id: 'st-7708', employeeId: 'A-7708', email: 'mohamed.risaal@macl.aero', name: 'Mohamed Risaal Rasheed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-03-25' },
  { id: 'st-8288', employeeId: 'A-8288', email: 'mohamed.shaikhan@macl.aero', name: 'Mohamed Shaikhan Shiham', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-06-15' },
  { id: 'st-10609', employeeId: 'A-10609', email: 'itp@macl.aero', name: 'Mohamed Shamikh Ahmed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-05' },
  { id: 'st-3968', employeeId: 'A-3968', email: 'moosa.reehan@macl.aero', name: 'Moosa Reehan', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2020-12-10' },
  { id: 'st-3287', employeeId: 'A-3287', email: 'nafiu.jameel@macl.aero', name: 'Nafiu Jameel', role: UserRole.ITP_SUPERVISOR, status: 'active', joinDate: '2020-08-25' },
  { id: 'st-7265', employeeId: 'A-7265', email: 'rajwan.ibrahim@macl.aero', name: 'Rajwan Ibrahim', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-12-15' },
  { id: 'st-7302', employeeId: 'A-7302', email: 'saif.mohamed@macl.aero', name: 'Saif Mohamed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-01-05' },
  { id: 'st-3162', employeeId: 'A-3162', email: 'samaan.moosa@macl.aero', name: 'Sam aan Moosa', role: UserRole.ITP_SUPERVISOR, status: 'active', joinDate: '2020-07-10' },
  { id: 'st-10608', employeeId: 'A-10608', email: 'itp@macl.aero', name: 'Moosa Aiman', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-02' },
  { id: 'st-8581', employeeId: 'A-8581', email: 'itp@macl.aero', name: 'Ali Muneef', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-07-20' },
  { id: 'st-7449', employeeId: 'A-7449', email: 'itp@macl.aero', name: 'Ismail Zabeeh', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-02-10' },
  { id: 'st-5055', employeeId: 'A-5055', email: 'itp@macl.aero', name: 'Ahmed Aslam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-04-18' },
  { id: 'st-7282', employeeId: 'A-7282', email: 'itp@macl.aero', name: 'Ahusan Abdulla', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-12-25' },
  { id: 'st-8369', employeeId: 'A-8369', email: 'itp@macl.aero', name: 'Ahmed Ibrahim', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-06-28' },
  { id: 'st-9168', employeeId: 'A-9168', email: 'itp@macl.aero', name: 'Ali Sinaan', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-10-05' },
  { id: 'st-7523', employeeId: 'A-7523', email: 'itp@macl.aero', name: 'Ahmed Naushad', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-02-28' },
  { id: 'st-10984', employeeId: 'A-10984', email: 'itp@macl.aero', name: 'Iz\'aan Shaukath', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-02-10' },
  { id: 'st-10985', employeeId: 'A-10985', email: 'itp@macl.aero', name: 'Ibrahim Sabooh Salah', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-02-12' },
  { id: 'st-6780', employeeId: 'A-6780', email: 'itp@macl.aero', name: 'Hassan Abdulla', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-01-22' },
  { id: 'st-2683', employeeId: 'A-2683', email: 'mohamed.gadir@macl.aero', name: 'Mohamed Abdul Gadir', role: UserRole.ITP_MANAGER, status: 'active', joinDate: '2019-07-15' },
  { id: 'st-8231', employeeId: 'A-8231', email: 'abdul.auf@macl.aero', name: 'Abdul Auf Mohamed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-01' },
  { id: 'st-8931', employeeId: 'A-8931', email: 'abdul.badeeu@macl.aero', name: 'Abdul Badeeu Najeeb', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-09-01' },
  { id: 'st-7649', employeeId: 'A-7649', email: 'abdulla.safwan@macl.aero', name: 'Abdulla Safwan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-03-10' },
  { id: 'st-8721', employeeId: 'A-8721', email: 'abdulla.shimaah@macl.aero', name: 'Abdulla Shimaah', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-07-30' },
  { id: 'st-5189', employeeId: 'A-5189', email: 'adam.haleem@macl.aero', name: 'Adam Haleem', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-05-01' },
  { id: 'st-7707', employeeId: 'A-7707', email: 'adam.shaiu@macl.aero', name: 'Adam Shaiu', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-03-22' },
  { id: 'st-4622', employeeId: 'A-4622', email: 'ahmedjailam@macl.aero', name: 'Ahmed Jailam', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-01-15' },
  { id: 'st-7621', employeeId: 'A-7621', email: 'ahmed.shahil@macl.aero', name: 'Ahmed Shahil Mohamed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-03-05' },
  { id: 'st-5146', employeeId: 'A-5146', email: 'ahmed.yoonus@macl.aero', name: 'Ahmed Yoonus', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-04-20' },
  { id: 'st-8366', employeeId: 'A-8366', email: 'ahmed.alham@macl.aero', name: 'Ahmed Alham Adil', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-25' },
  { id: 'st-7002', employeeId: 'A-7002', email: 'aiham.ibrahim@macl.aero', name: 'Aiham Ibrahim', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-12-05' },
  { id: 'st-9134', employeeId: 'A-9134', email: 'ali.mausoom@macl.aero', name: 'Ali Mausoom', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-09-25' },
  { id: 'st-0984', employeeId: 'A-0984', email: 'ali.nasheed@macl.aero', name: 'Ali Nasheed', role: UserRole.DEPOT_MANAGER, status: 'active', joinDate: '2018-03-12' },
  { id: 'st-7710', employeeId: 'A-7710', email: 'aliriza@macl.aero', name: 'Ali Riza', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-03-28' },
  { id: 'st-8357', employeeId: 'A-8357', email: 'ali.shareef1@macl.aero', name: 'Ali Shareef', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-20' },
  { id: 'st-8420', employeeId: 'A-8420', email: 'shafeeq.mansoor@macl.aero', name: 'Ali Shafeeq Mansoor', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-07-01' },
  { id: 'st-6604', employeeId: 'A-6604', email: 'haazim.mohamed@macl.aero', name: 'Haazim Mohamed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-02-12' },
  { id: 'st-7741', employeeId: 'A-7741', email: 'hamdhoonrasheed@macl.aero', name: 'Hamdhoon Rasheed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-04-02' },
  { id: 'st-4912', employeeId: 'A-4912', email: 'hassan.ameem@macl.aero', name: 'Hassan Ameem', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-03-01' },
  { id: 'st-6717', employeeId: 'A-6717', email: 'hassan.eenaaz@macl.aero', name: 'Hassan Eenaaz', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-01-18' },
  { id: 'st-3641', employeeId: 'A-3641', email: 'hassan.hussain@macl.aero', name: 'Hassan Hussain', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2020-11-25' },
  { id: 'st-8368', employeeId: 'A-8368', email: 'hussain.nishath@macl.aero', name: 'Hussain Nishath', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-26' },
  { id: 'st-8352', employeeId: 'A-8352', email: 'hussain.samau@macl.aero', name: 'Hussain Samau', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-18' },
  { id: 'st-6485', employeeId: 'A-6485', email: 'ibrahim.a@macl.aero', name: 'Ibrahim Ali', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-12-28' },
  { id: 'st-4909', employeeId: 'A-4909', email: 'mazeed.mohamed@macl.aero', name: 'Mazeed Mohamed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2021-02-28' },
  { id: 'st-8234', employeeId: 'A-8234', email: 'mohamed.afsan@macl.aero', name: 'Mohamed Afsan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-05' },
  { id: 'st-8287', employeeId: 'A-8287', email: 'moh.nihan@macl.aero', name: 'Mohamed Nihan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-06-14' },
  { id: 'st-8517', employeeId: 'A-8517', email: 'mohamed.sadhaan@macl.aero', name: 'Mohamed Sadhaan Ahmed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-07-10' },
  { id: 'st-8518', employeeId: 'A-8518', email: 'naail.abdulla@macl.aero', name: 'Naail Abdulla', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-07-12' },
  { id: 'st-6716', employeeId: 'A-6716', email: 'saifulla.nizar@macl.aero', name: 'Saifulla Nizar', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-01-16' },
  { id: 'st-7950', employeeId: 'A-7950', email: 'yoosuf.visam@macl.aero', name: 'Yoosuf Visam Latheef', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2022-04-28' },
  { id: 'st-35075', employeeId: '35075', email: 'mahmoodha@macl.aero', name: 'Mahamooda Shareef', role: UserRole.FINANCE, status: 'active', joinDate: '2020-02-01' },
  { id: 'st-1583', employeeId: 'A-1583', email: 'abdulla.saeed@macl.aero', name: 'Abdulla Saeed', role: UserRole.EXECUTIVE, status: 'active', joinDate: '2018-10-10' },
  { id: 'st-17019', employeeId: '17019', email: 'niyaz.mohamed@macl.aero', name: 'Mohamed Niyaz Jaufar', role: UserRole.FUEL_MANAGEMENT, status: 'active', joinDate: '2019-01-15' },
  { id: 'st-7709', employeeId: 'A-7709', email: 'ahmed.shaahee@macl.aero', name: 'Ahmed Shaahee', role: UserRole.COMMERCIAL, status: 'active', joinDate: '2022-03-26' },
  { id: 'st-8230', employeeId: 'A-8230', email: 'a.layaal@macl.aero', name: 'Aishath Layaal Khuzam', role: UserRole.COMMERCIAL, status: 'active', joinDate: '2022-05-30' },
  { id: 'st-1609', employeeId: 'A-1609', email: 'azzath.ghany@macl.aero', name: 'Azzath Abdul Ghanee', role: UserRole.FINANCE, status: 'active', joinDate: '2018-11-20' },
  { id: 'st-8569', employeeId: 'A-8569', email: 'shaaz.faiz@macl.aero', name: 'Shaaz Faiz', role: UserRole.FINANCE, status: 'active', joinDate: '2022-07-18' },
  { id: 'st-7546', employeeId: 'A-7546', email: 'fathimath.dhimna@macl.aero', name: 'Fathimath Dhimna Saeed', role: UserRole.FINANCE, status: 'active', joinDate: '2022-03-01' },
  { id: 'st-3041', employeeId: 'A-3041', email: 'mohamed.javeed@macl.aero', name: 'Mohamed Javeed', role: UserRole.COMMERCIAL, status: 'active', joinDate: '2020-04-12' },
  { id: 'st-9013', employeeId: 'A-9013', email: 'ahmed.hammad@macl.aero', name: 'Ahmed Hammad', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-09-10' },
  { id: 'st-7668', employeeId: 'A-7668', email: 'aminath.shazaa@macl.aero', name: 'Aminath Shazaa Rasheed', role: UserRole.COMMERCIAL, status: 'active', joinDate: '2022-03-12' },
  { id: 'st-7645', employeeId: 'A-7645', email: 'fathimath.shahnaz@macl.aero', name: 'Fathimath Shahnaz', role: UserRole.FINANCE, status: 'active', joinDate: '2022-03-08' },
  { id: 'st-6306', employeeId: 'A-6306', email: 'maid.mohamed@macl.aero', name: 'Maid Mohamed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2021-11-20' },
  { id: 'st-9115', employeeId: 'A-9115', email: 'mohamed.ahsham@macl.aero', name: 'Mohamed Ahsham Adam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2022-09-18' },
  { id: 'st-10721', employeeId: 'A-10721', email: 'itp@macl.aero', name: 'Abdul Qadir', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-3054', employeeId: 'A-3054', email: 'itp@macl.aero', name: 'Abdul Rahman Mohamed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6980', employeeId: 'A-6980', email: 'itp@macl.aero', name: 'Abdulla Ahmed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6836', employeeId: 'A-6836', email: 'itp@macl.aero', name: 'Ahmed Abdulla', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1361', employeeId: 'A-1361', email: 'itp@macl.aero', name: 'Ahmed Adam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1972', employeeId: '1972', email: 'itp@macl.aero', name: 'Ahmed Haneef', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-10607', employeeId: 'A-10607', email: 'itp@macl.aero', name: 'Ahmed Shaheen', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6746', employeeId: 'A-6746', email: 'itp@macl.aero', name: 'Ali Rashaadh', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-9116', employeeId: 'A-9116', email: 'itp@macl.aero', name: 'Eejaz Rasheed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8908', employeeId: 'A-8908', email: 'itp@macl.aero', name: 'Hoodhu Kamaal', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-10739', employeeId: 'A-10739', email: 'itp@macl.aero', name: 'Hussain Nasih', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-472', employeeId: '472', email: 'itp@macl.aero', name: 'Hussain Zareer', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-5701', employeeId: 'A-5701', email: 'itp@macl.aero', name: 'Ibrahim Ahmed Manik', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8387', employeeId: 'A-8387', email: 'itp@macl.aero', name: 'Ismail Adam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-2662', employeeId: 'A-2662', email: 'itp@macl.aero', name: 'Ismail Ali', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8633', employeeId: 'A-8633', email: 'itp@macl.aero', name: 'Ismail Waheed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-7483', employeeId: 'A-7483', email: 'itp@macl.aero', name: 'Mauman Aslam', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6133', employeeId: 'A-6133', email: 'itp@macl.aero', name: 'Mohamed Fayaz', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-5728', employeeId: 'A-5728', email: 'itp@macl.aero', name: 'Mohamed Ikleel', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-3052', employeeId: 'A-3052', email: 'itp@macl.aero', name: 'Mohamed Imaad', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-2709', employeeId: 'A-2709', email: 'itp@macl.aero', name: 'Mohamed Jameel', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-10740', employeeId: 'A-10740', email: 'itp@macl.aero', name: 'Mohamed Shareef', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-11072', employeeId: 'A-11072', email: 'itp@macl.aero', name: 'Moosa Ismail', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-3038', employeeId: 'A-3038', email: 'itp@macl.aero', name: 'Munaz Ali', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-9043', employeeId: 'A-9043', email: 'itp@macl.aero', name: 'Nishan Shakir', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1159', employeeId: 'A-1159', email: 'itp@macl.aero', name: 'Shareef Ibrahim', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8910', employeeId: 'A-8910', email: 'itp@macl.aero', name: 'Shifaan Shafiu', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-3166', employeeId: 'A-3166', email: 'itp@macl.aero', name: 'Tholal Mohamed', role: UserRole.ITP_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-5147', employeeId: 'A-5147', email: 'depot@macl.aero', name: 'Abdul Raheem Yoosuf', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8582', employeeId: 'A-8582', email: 'depot@macl.aero', name: 'Abdulla Irufaan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-10514', employeeId: 'A-10514', email: 'depot@macl.aero', name: 'Abdulla Riyaz', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-12449', employeeId: '12449', email: 'depot@macl.aero', name: 'Ahmed Ibrahim', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1301', employeeId: 'A-1301', email: 'depot@macl.aero', name: 'Ahmed Midshaan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8720', employeeId: 'A-8720', email: 'depot@macl.aero', name: 'Ahmed Nimal', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1468', employeeId: 'A-1468', email: 'depot@macl.aero', name: 'Ahmed Shafeeq', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-9587', employeeId: 'A-9587', email: 'depot@macl.aero', name: 'Ahmed Zayaan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6668', employeeId: 'A-6668', email: 'depot@macl.aero', name: 'Ali Hashim', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-14657', employeeId: '14657', email: 'depot@macl.aero', name: 'Ali Ibrahim', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-9030', employeeId: 'A-9030', email: 'depot@macl.aero', name: 'Easa Nasath Ibrahim', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-11035', employeeId: 'A-11035', email: 'depot@macl.aero', name: 'Hussain Shahuban Shiuth', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8351', employeeId: 'A-8351', email: 'depot@macl.aero', name: 'Ijhaadh Jaleel', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1998', employeeId: 'A-1998', email: 'depot@macl.aero', name: 'Ismail Mohamed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-1443', employeeId: 'A-1443', email: 'depot@macl.aero', name: 'Ismail Rasheed', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-7804', employeeId: 'A-7804', email: 'depot@macl.aero', name: 'Labeeb Ibrahim Ali', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-0707', employeeId: 'A-0707', email: 'depot@macl.aero', name: 'Mohamed Fairooz', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-10515', employeeId: 'A-10515', email: 'depot@macl.aero', name: 'Mohamed Naail', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6607', employeeId: 'A-6607', email: 'depot@macl.aero', name: 'Mohamed Saiban', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8233', employeeId: 'A-8233', email: 'depot@macl.aero', name: 'Mohamed Shamweel', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-5786', employeeId: 'A-5786', email: 'depot@macl.aero', name: 'Mohamed Shifau', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-0704', employeeId: 'A-0704', email: 'depot@macl.aero', name: 'Mohamed Thakhkhan', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-10064', employeeId: '10064', email: 'depot@macl.aero', name: 'Mohamed Moosa Fikry', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-6669', employeeId: 'A-6669', email: 'depot@macl.aero', name: 'Mohamed Nahud Ali', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' },
  { id: 'st-8875', employeeId: '8875', email: 'depot@macl.aero', name: 'Umaru Ibrahim', role: UserRole.DEPOT_OPERATOR, status: 'active', joinDate: '2023-01-01' }
];
